# Generated by Django 4.1.3 on 2023-01-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0003_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_stocks', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
