# Generated by Django 4.1.3 on 2023-01-31 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0005_alter_contact_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(default=1, upload_to='media/TimeZoneApp/Thumbnails<function user_directory_path at 0x7fe40042c9d0>'),
            preserve_default=False,
        ),
    ]
