# Generated by Django 4.1.3 on 2023-02-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0008_product_product_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price_currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
