# Generated by Django 4.1.3 on 2023-02-06 11:15

import TimeZoneApp.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0009_remove_product_product_price_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pno',
        ),
        migrations.AddField(
            model_name='product',
            name='product_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(upload_to=TimeZoneApp.models.user_directory_path),
        ),
    ]
