# Generated by Django 4.1.3 on 2023-02-06 11:39

import TimeZoneApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0010_remove_product_pno_product_product_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=TimeZoneApp.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeZoneApp.product')),
            ],
        ),
    ]
