# Generated by Django 4.1.3 on 2023-04-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeZoneApp', '0012_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
